name = "mtg-owner-comparison"
main = "src/index.ts"
compatibility_date = "2024-11-01"
type = "service-worker"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "mtg-owner-comparison"
preview = true
